### ISSUE TITLE
Data Team: Next Steps

### ISSUE THREAD

**Issue by jeremylang** [codeforboston/clean-slate-data#121]

**Comment by jeremylang** [comment]
Hey @mikemahoney218! Hope all is well. We’ve been wondering the status of the data team. Last I knew you met with Sana to discuss a good way to anonymize the data. We’ve had a few new members since who are interested in working on the data team and were wondering if you would be able to do a handoff? Thanks!

**Comment by mikemahoney218** [comment]
Hey! Sorry, quarantine and all has seen me kinda drop off the map for a lot of things, CfB included :grimacing: . More than happy to do a hand-off -- if there's anything immediate you're looking for input on, let me know, otherwise I'm happy to give people background (next Tuesday?). One thing to mention is that getting data from Sana (which, while we talked about anonymizing the data, I'm not sure what the timeline for getting said data was -- we talked about what we'd drop before handing it to people, but I never saw any data myself) made most of our other work moot -- if we have actual MA data to work with, we don't need to keep working on finding proxy states, because MA is the best proxy for MA. So if you all have heard more from Sana on actually getting that MA data then you likely know as much if not more than I do about what the data team needs to be working on -- we had paused most of our other threads in anticipation of this.

**Comment by jeremylang** [comment]
@mikemahoney218 no worries!

Thanks for the information, I'm understanding then that it's all about the the data from Sana - which I'm pretty sure I heard we got last week. It's supposed to be in the Google Drive somewhere.

There are two members of the team that are interested in the data side, I can double check if they are going to be attending the meeting on Tuesday (5/12). Feels like you are in the best position to provide background and hand-off if you can attend. I'll note though I am saying that having only a general knowledge of the data team. It went quiet around the time I got started with Clean Slate.

**Comment by mikemahoney218** [comment]
yup, if y'all have data from Sana, then that's what we would currently want to be working on -- and I don't really have much in the way of valuable input there, since we hadn't even seen the new data while I was around. Of course, happy to give background & whatever help I can -- let me know if the new data people are gonna be there Tuesday!

**Comment by jeremylang** [comment]
Hey @mikemahoney218 both people interested in the data team informed me they will be coming this Tuesday.

**Comment by jeremylang** [comment]
Hey @mikemahoney218, wondering if you would be able to attend our meeting tonight to take another shot at getting started with the new data from Sana? One of the team members interested confirmed they will be attending and the other might be able to make it half way through.

**Comment by mikemahoney218** [comment]
Hey! I'm sorry, I don't have access to a computer tonight, I'm currently recovering mine from a bit of a meltdown (on mobile atm). I can try for next week -- the big thing, if they're wondering what to do at all, is to try and find the number of people who only have expungeable offenses on their record but have > 1 of them. Using 5 years of data should be enough to capture anyone who offended in the first year of data and then reoffended -- after 4 years, recidivism reaches the same rates as the general population

**Comment by mikemahoney218** [comment]
As it is I haven't seen the data myself -- I think step 1 is gonna be figuring out what in the data can be used to try to identify an individual across multiple cases, since I don't believe there's an ID

**Comment by jeremylang** [comment]
@mikemahoney218 no worries and thanks for the next steps. Some of the team started looking into it tonight.

**Comment by MsPockets** [comment]
Sam and I are meeting tonight at 5 to go over what we were unable to get to last night.

Something that would be really useful to us is a list of which charges can be expunged. If we have one, or if we knew exactly what charges are expunge-able would be a massive help.

**Comment by mikemahoney218** [comment]
[This Google Doc](https://docs.google.com/spreadsheets/d/1RLvm-KuMZtkr0TPhHm0lukX4nHOqR_42jh2PScvyzek/edit?usp=sharing) contains a list of which crimes are and are not expungable.
